// Generated by Wrangler on Sun Jun 09 2024 00:10:41 GMT+0800 (China Standard Time)
// by running `wrangler types`

interface Env {
	ADMIN_ACCOUNT: "13974032066";
	PRISMA_ENV: "dev";
	DB: D1Database;
}
