// Generated by Wrangler on Sat Jun 08 2024 23:51:59 GMT+0800 (China Standard Time)
// by running `wrangler types`

interface Env {
	ADMIN_ACCOUNT: "13974032066";
	ENVIRONMENT: "dev";
	DB: D1Database;
}
