// Generated by Wrangler on Mon May 06 2024 22:52:01 GMT+0800 (China Standard Time)
// by running `wrangler types`

interface Env {
	WECHAT_APPID: "wx256067f403eec4d8";
	WECHAT_APP_SECRET: "38fc344e32b1ddf937644e3f82e49d83";
	DB: D1Database;
}
