#:schema node_modules/wrangler/config-schema.json
name = "simple-checklist"
compatibility_date = "2024-05-02"
pages_build_output_dir = "./build/client"

# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#d1-databases
# [[d1_databases]]
# binding = "MY_DB"
# database_name = "my-database"
# database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"


[vars]
WECHAT_APPID = "wx256067f403eec4d8"
WECHAT_APP_SECRET = "38fc344e32b1ddf937644e3f82e49d83"

######## PREVIEW environment config ########

[env.preview.vars]
WECHAT_APPID = "wx256067f403eec4d8"
WECHAT_APP_SECRET = "38fc344e32b1ddf937644e3f82e49d83"

######## PRODUCTION environment config ########

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "simple-checklist"
database_id = "98ab90ec-b337-4d1c-82ab-4a61a142250e"